/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Cipher {
  constructor(key?: Array<number> | undefined | null, nonce?: Array<number> | undefined | null)
  encrypt(data: string): Array<number>
  decrypt(data: Array<number>): string
  getKey(): Array<number>
  getNonce(): Array<number>
}
